### ISSUE TITLE
Spell Journal no longer functional

### ISSUE THREAD

**Issue by TempusVulpi** [Azami7/Ollivanders2#107]
The Spell Journal feature seems to have stopped working, as the changelog says nothing about it being removed i assume this is a bug, there don't seem to be any errors or feedback in the console.

**Comment by Azami7** [comment]
If I remember, we disabled it because we couldn't confirm it was working and suspected it might have been causing a different issue. I need to go back and look through the changes in the last couple versions to remember what was going on with that feature.

**Comment by Zundrel** [comment]
Both the spell journal and non-verbal spell features were removed by you in previous commits. I have re-added these features in a custom fork of the plugin https://github.com/Zundrel/Ollivanders-Reborn. Do note the spell journal uses some deprecated methods so it's probably best you re-write it to use updated methods. A long-standing issue with the non-verbal spells is the fact that scrolling through tends to move the list twice instead of once (i.e. pressing shift right-click and it going from 1 -> 3 on the list).

I'm willing to make a PR for these issues if you like, or you can implement them manually I'm in-different on the matter.

Note: I also added the ability to load the O2Players json instead of you only writing to it. Without this the Spell Journal was broken.

**Comment by Azami7** [comment]
Yep, these are both part of refactors that weren't finished for 2.2.5 but had gotten merged in accidentally. 

For the spell journal, there is a new command "/ollivanders2 summary" in 2.2.6 that anyone can run that will tell them all their spells plus their house and destined wand (if they have found it). 

For reading the json file, if you have the code then you see it is read in O2Players.java in loadO2Players(). You should see in the json file something like this for a player:

  "555731f0-a8df-4d61-8ecd-f5ba7ff06527": {
    "AVIS": "1",
    "INCENDIO": "1",
    "INCARNATIO_EQUUS": "1",
    "GEMINO": "1",
    "Wood": "Oak",
    "Souls": "0",
    "INCARNATIO_DEVITO": "1",
    "INCARNATIO_LUPI": "1",
    "Name": "§aAzami7",
    "DIFFINDO": "1",
    "INCARNATIO_LAMA": "1",
    "INCARNATIO_VACCULA": "1",
    "NOX": "1",
    "WINGARDIUM_LEVIOSA": "1",
    "INCARNATIO_PORCILLI": "1",
    "COLLOPORTUS": "1",
    "INCARNATIO_FELIS": "1",
    "ALOHOMORA": "1",
    "LUMOS": "1",
    "REPARO": "1",
    "Core": "Spider Eye",
    "REPARIFARGE": "1"
  },

Our server has been using the json files for players since September without issues between server restarts. I am wondering if there is some other reason your server is not reading the json file on server start. Did you see an error message?

Non-verbal spells needs to be reworked due to bugs in the implementation but we do not use it and I was testing disabling it entirely since it isn't really something we wanted to spend time fixing. If this is a feature you want to keep, it is probably best to rethink how it would ideally work and just write it over than make the existing one work the way it should.

**Comment by Azami7** [comment]
Crap, that bad merge was worse than I thought - the code for reading the json was not included. 

I have a new jar if either of you want to test it. We've been running most of this code for months but that only tells us it works for our environment. https://s3-us-west-2.amazonaws.com/pottercraft/Ollivanders2-2.2.6.jar

**Comment by Zundrel** [comment]
I know personally I would much prefer a book rather than a command for a few reasons such as immersiveness, easier accessibility (I don't want to type a command out every time I want to check my spells), and the fact it shows your house and destined wand is information which you wouldn't really need to know more than once.

**Comment by Azami7** [comment]
Actually, we get asked all the time what wand type a person has when they die and lose it and they don't remember what it was. As for house, agreed that should be something people wouldn't forget yet on our server we have had people get sorted then come back months later and not remember what they were sorted to. Since that is all of 2 lines in what will be many lines of output, we did not see this as a major inconvenience. 

Putting all the spells in a book is more in the spirit of the actual HP universe but the way it was implemented, people could not figure out unless given detailed instructions and it requires that the player has a book object to use. If you have thoughts on how this would ideally work from a player's perspective, that would be helpful.

**Comment by Azami7** [comment]
I should add, while a player may know this about themselves, and admin would not and this command will be expanded to allow an admin to get this information about any player. Version 2.2.6 is not complete yet so this has not been added.

**Comment by Zundrel** [comment]
I'm fine with the command in general, but not as a replacement for the spell journal. I'm mostly concerned about it telling your wand type, as personally I would prefer players not know their wand type until they actually go and have their wand choose them.

How is it any different than the other books other than the fact you're actually capable of making it by naming a book 'Spell Journal'. Lack of instructions is also a poor excuse because the same could be said for any other aspect of the mod unless the server actually gives them the information they need.

Not trying to argue, I just don't entirely get your points here.

**Comment by Azami7** [comment]
Point - it wasn't a well implemented feature, we don't use it on our server (and, honestly, we're doing this for us and as a side project), and it was using deprecated methods so we didn't have a reason to keep it. It is good to get the feedback that you do use it since we really have no way to know what others are doing with the plugin. When possible, I want the plugin to meet use cases of others but if we don't know them, give us a bit of patience and help us understand what you want to do.

I re-implemented this feature and I think it plays nicer. If you want to try it out, you can download the jar file from here - https://s3-us-west-2.amazonaws.com/pottercraft/Ollivanders2-2.2.6.jar

To use it - add a config flag "spellJournal" set to true, make a book named "Spell Journal", and then hold the book. The book will update itself any time it is held.

**Comment by Azami7** [comment]
I should note that the book text is nor fully formatted yet. If this works, I'll finish that up but I didn't want to write that code if the basic mechanics were still not right.

**Comment by Azami7** [comment]
Fix released with 2.2.6
