### ISSUE TITLE
Update your server

### ISSUE THREAD

**Issue by WhisperInTheNight** [Azami7/Ollivanders2#123]
Pretty please update your server. There isn't any guide to making the animagus potion and no spellbook to teach me how to apparate. Also could you please change the difficulty.

(PS, you're doing a great job with the plugin so far.)

Thanks!!

**Comment by autumnwoz** [comment]
We are working on a major re-factor of the way potions are done, so there aren't going to be instructions on potions until that is done.  If you want to know the instructions for making an animagus potion right now anyway we can tell you.  Thanks for pointing out apparate; I've added it to standard book of spells grade 6 so that will update when we do the new version of ollivanders.  What do you mean by change the difficulty?

**Comment by Azami7** [comment]
Version 2.2.7 of the plugin is now available - https://www.spigotmc.org/resources/ollivanders2.38992/update?update=240979

**Comment by Azami7** [comment]
Hi Whisper,

I am going to close this since we have not heard back from you in almost 2 months. Definitely re-open or file another issue if you have additional questions.
