### ISSUE TITLE
VENTO_FOLIO FIX

### ISSUE THREAD

**Issue by crazyshotgug69** [Azami7/Ollivanders2#176]
Not sure if it is just me being stupid at something...
But when I cast Vento Folio, it just shoots the glowstone out but does not make me fly or anything. Also Morsmordre, I cannot find it in any books. If there are fixes, or anything you can help me with these, please reply with it. Thanks.

**Comment by Azami7** [comment]
I'll play with vento folio and see if I can reproduce the issue you have. Morsmordre is indeed missing from a book. We'll have to think of a creative place to add this since in the HP universe this wouldn't have been in a book but something people learned from a Death Eater or Voldemort himself.

**Comment by crazyshotgug69** [comment]
Thank you, possibly a cool book idea (not from the universe, so I don't know if it is a great idea) would be like an ancient relic passed down through dark wizards perhaps. Not sure though. Also, if you can, don't worry if not, but could you perhaps lmk if you manage ro fix vento folio or something. Cheers :)

**Comment by crazyshotgug69** [comment]
Also, is the src on here updated every time the plugin is updated, or is it usually a little longer? :)

**Comment by Azami7** [comment]
Hi there, I should have read your vento folio comment more closely - you cannot target yourself with it. I tested and it does work fine when casting at others.

I like the book idea and there are lots of old dark magic books without name in the series so I think we can make something work.

Source on github is updated every time we finish adding and testing code on our server. We snapshot it to Spigot every few months once we've built up a fair number of changes. If you build from the source here it will always be the most current.

**Comment by crazyshotgug69** [comment]
Thank you, any way I can edit it to allow it to work on myself?

**Comment by Azami7** [comment]
My assumption is that Vento Folio was added by the original author to be the [Flying Charm](http://harrypotter.wikia.com/wiki/Flying_charm), however this shouldn't even be used on people since it is meant to make brooms, carpets, or cars (in Mr Weasley's case) fly but MC doesn't have a game mechanic for making non-entities fly. 

We had been looking at removing this spell since wizards cannot, generally, make themselves fly and Voldemort being able to do so in Deathly Hallows was a huge deal. Flying would then be pretty sophisticated magic, possibly dark, magic and it is never explained how he does this. A correct refactor of this would make it a self-targeting spell but also very hard to learn/cast.

Take a look at how Amato Animo Animato Animagus works to see how you'd have a spell set an effect on yourself rather than others.

**Comment by crazyshotgug69** [comment]
Ah yes, I guess it would be cool if it was still there but very hard to learn etc. I don't think Vento Folio is even a thing at that, it was just a power that certain order members and certain death eaters had.
