### ISSUE TITLE
1.13.2 Version error last release

### ISSUE THREAD

**Issue by Prowco** [Azami7/Ollivanders2#331]
I use paper 1.13.2 and the lastest version u release its not compatible display a error on server opening
Server log:  https://mclo.gs/O9O7nLg

**Comment by Azami7** [comment]
Hi Prowco, you can override the version check by using the config setting:

overrideVersionCheck: true

Please be aware that the version check is added where we have not verified that the plugin works. Definitely let us know if it works for you.

**Comment by Prowco** [comment]
Well thats not a solution bc the plugin even make the folder with config file so i can change that option.

**Comment by Azami7** [comment]
If you have no plugin directory, it will create it and the config file the first time. Once it exists, you can update the config file as desired. 

Please keep in mind that 1.13.2 is not API compatible with 1.14 and later so even if you change this setting, I am not sure spigot will load the plugin because the plugin uses classes and methods not available in 1.13.2. You can tell if it is spigot not loading it or the plugin disabling itself on the version check by the log message. The plugin running the version check and disabling should say "This version of Ollivanders2 requires 1.14 or higher." 

If spigot does it, it will be at the very beginning and will say org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.14

**Comment by Azami7** [comment]
We just posted a minor update to Ollivanders 2.3. This version support MC 1.13 and should work for your server. 

https://www.spigotmc.org/resources/ollivanders2.38992/update?update=364147
