### ISSUE TITLE
Hi! Console spawm / not working error

### ISSUE THREAD

**Issue by Zsombi12** [Azami7/Ollivanders2#353]
When i reload my server the plugin start spamming the console, and in game the commands not work. 
I use: Ollivanders2-2.3.2.jar
I use on: 1.13 ( SPIGOT )
Thankx for the answer.
Log: (i uploaded to a file): https://easyupload.io/u2bpy3

**Comment by Azami7** [comment]
Hi Zsombi12,

Thanks for the log file. It looks like that may be an older build of 2.3.2 since the line numbers in the stack traces do not line up with the code anymore but I think I found the issue (I definitely found an issue). 

See if this jar file works: https://pottercraft.s3-us-west-2.amazonaws.com/Ollivanders2/Ollivanders2-2.3.3.jar

If you see additional errors, just paste the first stack trace as a reply on this issue. That should be easier than uploading the whole log file.

**Comment by Azami7** [comment]
I do not know what plugman is but I believe this error is caused by using an older version of Java. I have no problems using this jar on a clean install of spigot-1.13.2.

What version of Java are you running?

**Comment by Azami7** [comment]
Resolving since there has been no response from the submitter in 3 weeks. Please re-open if you continue to have issues.
